### ISSUE TITLE
Cachebox ACB2-20190922-3424 friert ein

### ISSUE THREAD

**Issue by nothelfer** [Ging-Buh/cachebox#3]
Cachebox ACB2-20190922-3424 friert ein

- Das Programm startet

- der Bildschirm wird nicht voll von ACB abgedeckt: oben erscheint ein weißer Balken 

- bei Klick auf die Bedientasten passiert nichts

- auch Ausschalten funzt nicht

Screenshot und 
[log_2019.09.25._05_27_40.txt](https://github.com/Ging-Buh/cachebox/files/3650453/log_2019.09.25._05_27_40.txt)
[log_2019.09.25._05_28_12.txt](https://github.com/Ging-Buh/cachebox/files/3650454/log_2019.09.25._05_28_12.txt)
[log_2019.09.25._05_33_16.txt](https://github.com/Ging-Buh/cachebox/files/3650455/log_2019.09.25._05_33_16.txt)
![Screenshot_2019-09-25 ACB](https://user-images.githubusercontent.com/8603264/65567694-70da1500-df57-11e9-981f-c5c85356596b.jpg)

**Comment by arbor95** [comment]
Das wundert mich etwas, weil der Screenshot nicht zu den Logs passt.
In den Logs steht nämlich noch nicht drin, das das Hauptprogramm (Main) gestartet wurde.

Du hast (wohl) die Frage nach dem Arbeitsbereich eingeschaltet.
Da muss ich mir diesen Codeteil wohl noch mal näher anschauen.
Bei meinen bisherigen Tests ist mir da kein Problem aufgefallen.

Wurdest du schon nach dem Arbeitsbereich gefragt?

**Comment by arbor95** [comment]
Da ist in der configDB wohl ein anderer Arbeitsbereich eingestellt.
Hast du die Frage nach dem Arbeitsbereich eingeschaltet?

**Comment by arbor95** [comment]
Der Umbau ist abgeschlossen.
